FROM gradle:8.13-jdk21 AS build

WORKDIR /app

COPY . .

RUN gradle :scheduler:bootJar --no-daemon

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/scheduler/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
